plugins {
    id 'java'
    id 'org.checkerframework' version '1.0.2'
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly fileTree(dir: '/Users/mushfiqurrahmanchowdhury/eventbus-deps', include: '*.jar')
}

sourceSets {
    main {
        java {
            srcDirs = ['.']
            include 'org/**/*.java'
        }
    }
}

checkerFramework {
    checkers = ['org.checkerframework.checker.nullness.NullnessChecker']
    extraJavacArgs = ['-Xmaxwarns', '10000', '-Awarns']
    version = '4.2.0'
}

tasks.withType(JavaCompile).configureEach {
    options.fork = true
    options.forkOptions.memoryMaximumSize = '4g'
}
