import net.ltgt.gradle.errorprone.CheckSeverity

apply plugin: 'java'
apply plugin: 'net.ltgt.errorprone'
group = rootProject.group
version = rootProject.version

java.sourceCompatibility = JavaVersion.VERSION_1_8
java.targetCompatibility = JavaVersion.VERSION_1_8

sourceSets {
    main {
        java {
            srcDir 'src'
            // exclude 'de/greenrobot/event/util/**'
        }
    }
}

def annotatorOutDir = "${rootProject.projectDir.absolutePath}/annotator-out"
dependencies {
    errorprone "com.google.errorprone:error_prone_core:2.14.0"
    annotationProcessor "com.uber.nullaway:nullaway:0.10.10"
    annotationProcessor "edu.ucr.cs.riple.annotator:annotator-scanner:1.3.15"
    compileOnly "com.uber.nullaway:nullaway-annotations:0.10.10"
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
    compileOnly "org.jspecify:jspecify:0.3.0"
}
tasks.withType(JavaCompile).configureEach {
    if (!name.toLowerCase().contains("test")) {
        options.errorprone {
            check("NullAway", CheckSeverity.WARN)
            check("AnnotatorScanner", CheckSeverity.ERROR)
            option("NullAway:AnnotatedPackages", "org.greenrobot.eventbus")
            option("NullAway:SerializeFixMetadata", "true")
            option("NullAway:FixSerializationConfigPath", "${annotatorOutDir}/nullaway.xml")
            option("AnnotatorScanner:ConfigPath", "${annotatorOutDir}/scanner.xml")
        }
        options.compilerArgs << "-Xmaxerrs" << "100000"
        options.compilerArgs << "-Xmaxwarns" << "100000"
    }
}

javadoc {
    failOnError = false
    title = "EventBus ${version} API"
	options.bottom = 'Available under the Apache License, Version 2.0 - <i>Copyright &#169; 2012-2020 <a href="https://greenrobot.org">greenrobot.org</a>. All Rights Reserved.</i>'
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    archiveClassifier.set("javadoc")
    from 'build/docs/javadoc'
}

task sourcesJar(type: Jar) {
    archiveClassifier.set("sources")
    from sourceSets.main.allSource
}

apply from: rootProject.file("gradle/publish.gradle")
// Set project-specific properties
afterEvaluate {
    publishing.publications {
        mavenJava(MavenPublication) {
            artifactId = "eventbus-java"

            from components.java
            artifact javadocJar
            artifact sourcesJar
            pom {
                name = "EventBus"
                description = "EventBus is a publish/subscribe event bus."
                packaging = "jar"
            }
        }
    }
}
